### ISSUE TITLE
[BUG]: Pull request checkList update

### ISSUE THREAD

**Issue by mfsisudhanshuk** [mindfiredigital/PivotHead#41]
### Describe the bug

Before creating pull you should check some codebase guidelines to be followed :- 

### Checklist:

- [ ] [Specific task related to the feature]
- [ ] [Another specific task]
- [ ] Ensure all components are properly typed with TypeScript.
- [ ] Add or update unit tests for new functionality.
- [ ] Update documentation (comments, README, etc.) to reflect changes.
- [ ] The file(s) or folder(s) now contain changes as specified in the issue I worked on.
//Newely added
- [ ] Check build, test, lint and format by run running command `pnpm run build` at root directory.
- [ ] I certify that I ran the checklist.

### Steps to reproduce

NO

### Expected behavior

Must pass this checklist 
- [ ] Check build, test, lint and format by run running command `pnpm run build` at root directory.

### What is actually happening?

Skipping it while creating PR 
- [ ] Check build, test, lint and format by run running command `pnpm run build` at root directory.
